ZSH_BASE=$HOME/.dotfiles
source $ZSH_BASE/antigen/antigen.zsh

export EDITOR=vim
export LC_ALL=C
export LANG=C
export CLICOLOR=1
export LINKS_REPO="mewil/codex"
export GPG_TTY=$(tty)

# PATH
export GOPATH=$HOME/go/
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin
export PATH=$PATH:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
export PATH=$PATH:/Applications/Wireshark.app/Contents/MacOS:$HOME/go/bin
export PATH=$PATH:/opt/local/bin:/opt/local/sbin

antigen use oh-my-zsh

antigen bundle aws
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle copyfile
antigen bundle docker
antigen bundle docker-compose
antigen bundle doctl
antigen bundle fd
antigen bundle fzf
antigen bundle gcloud
antigen bundle git
antigen bundle git-auto-fetch
antigen bundle golang
antigen bundle helm
antigen bundle kubectl
antigen bundle node
antigen bundle npm
antigen bundle pip
antigen bundle python
antigen bundle react-native
antigen bundle ripgrep
antigen bundle rust
antigen bundle tmux
antigen bundle yarn
antigen bundle z
antigen bundle zsh-interactive-cd
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

case `uname` in
  Darwin)
    antigen bundle macos
    antigen bundle brew
  ;;
esac

antigen apply

source ~/.aliases.sh
source ~/.prompt.sh

# Initialize completion
# autoload -Uz compinit && compinit -i
# zstyle ':completion:*' menu select=4
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# zmodload zsh/complist

# Enable interactive comments (# on the command line)
setopt interactivecomments

# Nicer history
HISTSIZE=1048576
HISTFILE="$HOME/.zsh_history"
SAVEHIST=$HISTSIZE
setopt appendhistory
setopt incappendhistory
setopt extendedhistory

GIT_AUTO_FETCH_INTERVAL=1200 # 20 minutes in seconds
